### ISSUE TITLE
コードをもとに進捗管理を行うスクリプトの作成

### ISSUE THREAD

**Issue by ghost** [kentakom1213/kyopro#4]
概要
入力:  追加したコード
出力:  問題とAC状況を難易度別 (A, B, C, D...)、種類別 (bit, DP, graph...)にまとめたcsvファイル
　　　概要を書いたmdファイル

**Comment by poweller** [comment]
gatsbyとかでwebサイトにしてみてもいいかもしれない

**Comment by kentakom1213** [comment]
Notionで考察することにした
